# .github/workflows/verificar-acoes.yml
name: Verificar ações pendentes

on:
  schedule:
    - cron: '*/1 * * * *' # A cada 1 minuto
  workflow_dispatch:

jobs:
  verificar:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar ações pendentes
        run: curl -X GET "https://ganhesocial.com/api/verificar-acoes"

