name: Verificar Ações Pendentes

on:
  repository_dispatch:
    types: [verificar-acoes]

jobs:
  ping-verificacao:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar requisição para verificar ações
        run: |
          curl -X GET "https://ganhesocial.com/api/verificar-acoes"
