name: Verificar Ações Pendentes

on:
  schedule:
    - cron: "*/5 * * * *" # A cada 5 minutos
  workflow_dispatch: # permite rodar manualmente também

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Chamar a rota de verificação de ações
        run: |
          curl -X GET "https://ganhesocial.com/api/verificar-acoes"
